name: Weather Today Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Build (Production)
      env:
        URL_MAIN: ${{ secrets.URL_MAIN }}
        URL_MAIN_KEY: ${{ secrets.URL_MAIN_KEY }}
        URL_SUGGESTION: ${{ secrets.URL_SUGGESTION }}
      run: npm run build:prod
